Q1. Subset the dataset Orders to create a dataset with only “Online” payment.

In [1]:
df <- read.csv("Orders.csv")
head(df)

  Order.ID  Order.Date Place.of.Shipment Payment.Terms
1 32 90 001 31-Dec-10  Pune              Cheque
2 32 90 002 6-Jan-11   Nasik             Online
3 32 90 003 14-Jan-11  Ahmednagar        Cash
4 32 90 004 18-Feb-11  Nanded            Cheque
5 32 90 005 19-Feb-11  Kolhapur          Cash
6 32 90 006 1-Mar-11   Buldhana          Online

In [2]:
subset(df, Payment.Terms=="Online")

   Order.ID  Order.Date Place.of.Shipment Payment.Terms
2  32 90 002 6-Jan-11   Nasik             Online
6  32 90 006 1-Mar-11   Buldhana          Online
7  32 90 007 4-Mar-11   Nasik             Online
8  32 90 008 15-Mar-11  Pune              Online
9  32 90 009 19-Mar-11  Mumbai            Online
10 32 90 010 29-Mar-11  Thane             Online
11 32 90 011 12-Apr-11  Ratnagiri         Online
12 32 90 012 14-Apr-11  Raigad            Online
18 32 90 018 14-Aug-11  Aurangabad        Online
22 32 90 022 28-Sep-11  Ratnagiri         Online
23 32 90 023 12-Oct-11  Raigad            Online
26 32 90 026 20-Nov-11  Dhule             Online
27 32 90 027 11-Dec-11  Pune              Online
28 32 90 028 14-Dec-11  Mumbai            Online
29 32 90 029 30-Dec-11  Aurangabad        Online
37 32 90 037 22-Apr-12  Goa               Online
38 32 90 038 14-May-12  Solapur           Online
39 32 90 039 15-May-12  Sangli            Online
40 32 90 040 19-Jun-12  Satara            Online
41 32 90 041 23-Jul-12  Aurangabad        Online
48 32 90 048 23-Nov-12  Nasik             Online
49 32 90 049 14-Dec-12  Ahmednagar        Online
50 32 90 050 19-Dec-12  Nanded            Online
51 32 90 051 23-Dec-12  Kolhapur          Online
59 32 90 059 14-Apr-13  Sindhudurga       Online
60 32 90 060 14-Apr-13  Goa               Online
61 32 90 061 24-Apr-13  Solapur           Online
62 32 90 062 13-May-13  Sangli            Online
68 32 90 068 2-Aug-13   Ratnagiri         Online

Q2. Consider the dataset mtcars. Output (write) the data in this data set into a csv file and name the csv file as
mtcars.csv.

In [3]:
df <- data(mtcars)
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [4]:
write.csv(mtcars, "mtcars.csv")

Q3. Consider the dataset diamonds. Subset the dataset with criteria as cut=Premium and color=J

In [5]:
df <- read.csv2("Diamonds.csv")
head(df)

  carat cut       color clarity depth table price x    y    z
1 0.23  Ideal     E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium   E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.23  Good      E     VS1     56.9  65    327   4.05 4.07 2.31
4 0.29  Premium   I     VS2     62.4  58    334   4.20 4.23 2.63
5 0.31  Good      J     SI2     63.3  58    335   4.34 4.35 2.75
6 0.24  Very Good J     VVS2    62.8  57    336   3.94 3.96 2.48

In [6]:
subset(df, cut=="Premium" & color=="J")

      carat cut     color clarity depth table price x    y    z
57    0.30  Premium J     SI2     59.3  61     405  4.43 4.38 2.61
325   1.00  Premium J     SI2     62.3  58    2801  6.45 6.34 3.98
367   0.93  Premium J     SI2     61.9  57    2807  6.21 6.19 3.84
526   1.17  Premium J     I1      60.2  61    2825  6.90 6.83 4.13
745   0.33  Premium J     VS1     62.8  58     557  4.41 4.38 2.76
746   0.33  Premium J     VS1     61.5  61     557  4.46 4.39 2.72
766   0.92  Premium J     SI1     62.9  58    2858  6.22 6.18 3.90
814   0.91  Premium J     SI1     59.5  62    2863  6.40 6.18 3.74
815   0.90  Premium J     VS2     59.8  62    2863  6.24 6.21 3.72
861   0.90  Premium J     SI1     62.8  59    2871  6.13 6.03 3.82
882   0.90  Premium J     SI1     61.8  58    2873  6.16 6.13 3.80
886   0.90  Premium J     SI1     60.9  61    2873  6.26 6.22 3.80
1000  1.12  Premium J     SI2     60.6  59    2898  6.68 6.61 4.03
1039  0.91  Premium J     SI1     62.8  59    2905  6.19 6.14 3.87
1361  0.90  Premium J     VS1     62.1  62    2964  6.12 6.05 3.78
1511  1.24  Premium J     I1      61.9  55    2994  6.92 6.85 4.26
1826  0.91  Premium J     VS2     61.6  58    3058  6.28 6.23 3.85
1844  0.93  Premium J     VS1     60.3  58    3062  6.37 6.31 3.82
1974  0.92  Premium J     VS2     60.9  62    3091  6.31 6.26 3.83
2118  1.02  Premium J     SI2     62.3  58    3119  6.42 6.37 3.98
2146  0.93  Premium J     VS2     61.1  59    3125  6.34 6.32 3.87
2207  0.90  Premium J     SI1     60.4  59    3141  6.27 6.24 3.78
2251  1.03  Premium J     SI2     62.2  59    3149  6.42 6.40 3.99
2275  1.22  Premium J     SI2     62.6  59    3156  6.79 4.24 3.76
2364  0.90  Premium J     VS1     62.3  56    3175  6.23 6.19 3.87
2445  0.96  Premium J     SI1     62.9  59    3187  6.30 6.22 3.94
2457  1.01  Premium J     VS2     62.4  60    3190  6.45 6.35 3.99
2586  1.10  Premium J     SI2     60.0  58    3216  6.77 6.66 4.03
2760  0.93  Premium J     VS2     62.3  60    3250  6.30 6.23 3.90
2825  1.12  Premium J     SI2     60.7  61    3266  6.71 6.64 4.05
⋮     ⋮     ⋮       ⋮     ⋮       ⋮     ⋮     ⋮     ⋮    ⋮    ⋮
49556 0.81  Premium J     VS2     60.6  60    2129  6.04 6.00 3.65
49630 0.32  Premium J     VS1     60.6  59     540  4.46 4.42 2.69
49631 0.32  Premium J     VS1     61.9  58     540  4.39 4.33 2.70
49632 0.32  Premium J     VS1     61.7  58     540  4.40 4.38 2.71
49716 0.76  Premium J     VS1     61.1  58    2148  5.85 5.91 3.59
49721 0.70  Premium J     IF      60.5  59    2150  5.67 5.73 3.45
49836 0.82  Premium J     SI1     61.2  58    2168  5.99 6.04 3.68
50011 0.95  Premium J     I1      61.7  59    2195  6.32 6.26 3.88
50042 0.81  Premium J     SI1     61.8  57    2199  6.02 5.96 3.70
50044 0.79  Premium J     SI1     59.1  57    2199  6.08 6.06 3.59
50064 0.80  Premium J     VS1     61.6  60    2202  5.94 5.88 3.64
50073 0.72  Premium J     VVS1    61.4  61    2203  5.77 5.70 3.52
50205 0.80  Premium J     SI1     60.1  57    2227  6.03 5.98 3.61
50288 0.36  Premium J     SI1     61.3  60     541  4.59 4.52 2.79
50332 0.83  Premium J     SI2     59.1  60    2241  6.13 6.12 3.62
50436 0.76  Premium J     VS1     61.1  58    2262  5.91 5.85 3.59
50459 0.70  Premium J     IF      60.5  59    2264  5.73 5.67 3.45
50601 0.82  Premium J     SI1     61.2  58    2283  6.04 5.99 3.68
50708 0.80  Premium J     VS1     60.8  59    2292  6.00 5.94 3.63
50730 0.85  Premium J     VS2     60.7  58    2295  6.12 6.08 3.71
50849 0.83  Premium J     SI1     62.8  58    2311  6.00 5.95 3.75
50951 0.87  Premium J     SI1     61.4  57    2321  6.17 6.14 3.78
51195 0.81  Premium J     VS1     61.7  61    2350  5.94 5.90 3.65
51581 1.03  Premium J     I1      62.8  55    2392  6.43 6.41 4.03
52255 1.01  Premium J     I1      60.7  59    2488  6.39 6.42 3.89
53032 1.01  Premium J     I1      60.7  59    2602  6.42 6.39 3.89
53495 1.01  Premium J     SI2     58.3  62    2683  6.49 6.43 3.77
53499 1.01  Premium J     SI2     59.3  56    2683  6.51 6.45 3.84
53692 0.90  Premium J     SI2     62.7  57    2717  6.09 6.06 3.80
53700 0.90  Premium J     SI2     63.0  59    2717  6.14 6.11 3.86

Q4. Consider the dataset diamonds. Create a data frame object which stores just variables carat, color, depth and price

In [7]:
df2 <- subset(df, select=c(carat, color, depth, price))
head(df2)

  carat color depth price
1 0.23  E     61.5  326
2 0.21  E     59.8  326
3 0.23  E     56.9  327
4 0.29  I     62.4  334
5 0.31  J     63.3  335
6 0.24  J     62.8  336

Q5. Consider the dataset mtcars. Choose the 2nd, 18th, 30th and 12th rows

In [8]:
mtcars[c(2, 18, 30, 12),]

              mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4 Wag 21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Fiat 128      32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Ferrari Dino  19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Merc 450SE    16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3